name: Monitoraggio Gotomare
on:
  schedule:
    # Esegue il test ogni 30 minuti (al minuto 0 e al minuto 30)
    - cron: '*/30 * * * *' 
  workflow_dispatch: # Ti permette di farlo partire a mano quando vuoi

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Eliminiamo il warning forzando l'uso di Node 24
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24 # Aggiornato alla versione richiesta
      - name: Install dependencies
        run: |
          npm init -y
          npm install @playwright/test
          npx playwright install chromium --with-deps
      - name: Run Tests
        run: npx playwright test
