name: Monitoraggio Gotomare
on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora esatta
  workflow_dispatch: # Permette di farlo partire a mano per provare

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm init -y
          npm install @playwright/test
          npx playwright install chromium --with-deps
      - name: Run Tests
        run: npx playwright test
